.TH "SPROXYD" "1" "AUGUST 2015" "russkubik@gmail.com" "User Manuals"
.SH "NAME"
sproxyd \- Serial port virtualization daemon
.SH "SYNOPSIS"
\fBsproxyd\fR [\fIOPTIONS\fR]
.SH "DESCRIPTION"
Daemon that proxies data from any number of physical serial ports to virtual
pseudoterminals.
.SH "OPTIONS"
.TP
\fB-d\fR
Run the utility in the background.
.br
.TP
\fB-c\fR
.br
PATH to config file.
.br
.TP
\fB-v\fR
.br
Print version and quit.
.br
.TP
\fB-h\fR
.br
Program usage.
.br
.SH SEE ALSO
.BR serial-proxy (5)
.br
.SH AUTHOR
sproxyd was written by Russ Kubik <russkubik@gmail.com>.
.PP
This manual page was written by Russ Kubik <russkubik@gmail.com>
